INSERT INTO vacancies (name, description, salary, exp_from, exp_to, is_active, category_id, author_id, created_date, update_time)
VALUES
    ('Java Developer', 'Работа в крупном банке, знание Spring Boot.', 150000, 1, 3, true, (select ID from CATEGORIES where CATEGORIES.NAME = 'IT'), (select ID from USERS_TABLE where USERS_TABLE.EMAIL = 'qwe@qwe.qwe'), now(), now()),
    ('Python Engineer', 'Разработка ML моделей.', 180000, 2, 5, true, (select ID from CATEGORIES where CATEGORIES.NAME = 'IT'), (select ID from USERS_TABLE where USERS_TABLE.EMAIL = 'qwe@qwe.qwe'), now(), now()),
    ('Frontend Developer', 'React, TypeScript и Tailwind.', 120000, 0, 2, true, (select ID from CATEGORIES where CATEGORIES.NAME = 'Software Development'), (select ID from USERS_TABLE where USERS_TABLE.EMAIL = 'qwe@qwe.qwe'), now(), now()),
    ('Project Manager', 'Управление IT-проектами.', 100000, 3, 6, true, (select ID from CATEGORIES where CATEGORIES.NAME = 'Web Development'), (select ID from USERS_TABLE where USERS_TABLE.EMAIL = 'qwe@qwe.qwe'), now(), now()),
    ('QA Automation', 'Тестирование на Java/Selenium.', 110000, 1, 3, true, (select ID from CATEGORIES where CATEGORIES.NAME = 'IT'), (select ID from USERS_TABLE where USERS_TABLE.EMAIL = 'qwe@qwe.qwe'), now(), now()),
    ('UI/UX Designer', 'Проектирование интерфейсов мобильных приложений.', 95000, 2, 4, true, (select ID from CATEGORIES where CATEGORIES.NAME = 'Software Development'), (select ID from USERS_TABLE where USERS_TABLE.EMAIL = 'qwe@qwe.qwe'), now(), now()),
    ('DevOps Engineer', 'Настройка CI/CD и Kubernetes.', 200000, 3, 5, true, (select ID from CATEGORIES where CATEGORIES.NAME = 'IT'), (select ID from USERS_TABLE where USERS_TABLE.EMAIL = 'misha1980@mail.ru'), now(), now()),
    ('HR Manager', 'Поиск и подбор персонала в IT.', 70000, 1, 3, true, (select ID from CATEGORIES where CATEGORIES.NAME = 'Web Development'), (select ID from USERS_TABLE where USERS_TABLE.EMAIL = 'qwe@qwe.qwe'), now(), now()),
    ('System Administrator', 'Поддержка офисной сети.', 60000, 0, 3, true, (select ID from CATEGORIES where CATEGORIES.NAME = 'IT'), (select ID from USERS_TABLE where USERS_TABLE.EMAIL = 'qwe@qwe.qwe'), now(), now()),
    ('Analyst', 'Сбор и анализ требований.', 90000, 2, 4, true, (select ID from CATEGORIES where CATEGORIES.NAME = 'Web Development'), (select ID from USERS_TABLE where USERS_TABLE.EMAIL = 'qwe@qwe.qwe'), now(), now()),
    ('PHP Developer', 'Поддержка legacy проектов на Laravel.', 100000, 2, 5, true, (select ID from CATEGORIES where CATEGORIES.NAME = 'IT'), (select ID from USERS_TABLE where USERS_TABLE.EMAIL = 'qwe@qwe.qwe'), now(), now()),
    ('Mobile Developer (Flutter)', 'Кроссплатформенная разработка.', 140000, 1, (select ID from CATEGORIES where CATEGORIES.NAME = 'Web Development'), true, (select ID from CATEGORIES where CATEGORIES.NAME = 'IT'), (select ID from USERS_TABLE where USERS_TABLE.EMAIL = 'qwe@qwe.qwe'), now(), now()),
    ('Copywriter', 'Написание текстов для IT-блога.', 50000, 0, 2, true, (select ID from CATEGORIES where CATEGORIES.NAME = 'Software Development'), (select ID from USERS_TABLE where USERS_TABLE.EMAIL = 'qwe@qwe.qwe'), now(), now()),
    ('Database Admin', 'Оптимизация PostgreSQL.', 170000, 3, 6, true, (select ID from CATEGORIES where CATEGORIES.NAME = 'IT'), (select ID from USERS_TABLE where USERS_TABLE.EMAIL = 'qwe@qwe.qwe'), now(), now()),
    ('Team Lead Java', 'Руководство командой разработки.', 250000, 5, 10, true, (select ID from CATEGORIES where CATEGORIES.NAME = 'IT'), (select ID from USERS_TABLE where USERS_TABLE.EMAIL = 'qwe@qwe.qwe'), now(), now());